### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by mhartington** [chemzqm/redismru.vim#1]
I have redis installed, node installed, and I'm installing the plugin with dein.vim, everything seems to have been installed correctly, but I'm getting this error

['Could not connect to Redis at 127.0.0.1:6379: Connection refused', '']

Any idea?

**Comment by chemzqm** [comment]
@mhartington check your redis running by command:

```
redis-cli -h 127.0.0.1 -p 6379`
```

You may need to change the port by

```
let g:redismru_port=port_number
```

You can make redis run at your system start with command like:

```
launchctl load -w ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
```

on Mac

**Comment by mhartington** [comment]
Yeah seems that if I manually start redis up myself, everything works fine. 
Is that something I need to do or should the plugin take care of that for me?

**Comment by chemzqm** [comment]
@mhartington plugin should not do that, it's system configuration job, you can search for auto start redis in your system on google.

**Comment by mhartington** [comment]
Cool, thanks for the clarification. Nice work on the plugin!
